# Generated by Django 3.0.8 on 2020-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payid', models.IntegerField()),
                ('name', models.CharField(max_length=64, verbose_name='FeeName')),
                ('fee', models.IntegerField()),
                ('paydate', models.DateTimeField(auto_now_add=True, verbose_name='Paydate')),
            ],
        ),
    ]
