# Generated by Django 2.1.8 on 2021-08-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=800, verbose_name='Content'),
        ),
    ]
